name: Build and deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: normalize-ref
        name: Normalize ref
        env:
          ref: ${{ github.ref_name }}
        run: |
          echo "normalized_ref_name=$(lower=${ref//\//-} && echo ${lower,,})" >> ${GITHUB_OUTPUT}

      - id: docker-metadata
        name: Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}
          flavor: |
            latest=false
            prefix=${{ secrets.DOCKER_TAG_PREFIX }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          build-args: |
            version=${{ steps.normalize-ref.outputs.normalized_ref_name }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          push: true
