name: Pull Request

on:
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        uses: eviive/actions/validate/format/prettier@main

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ESLint
        uses: eviive/actions/validate/lint/eslint@main
