name: Pull Request

on:
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        uses: eviive/actions/validate/format/prettier@main
        with:
          plugins: prettier-plugin-tailwindcss@~0.6.14

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ESLint
        uses: eviive/actions/validate/lint/eslint@main
        with:
          version: ~9.32.0
          plugins: >-
            @eslint/js@~9.32.0
            eslint-config-prettier@~10.1.8
            eslint-import-resolver-typescript@~4.4.4
            eslint-plugin-import@~2.32.0
            eslint-plugin-jsx-a11y@~6.10.2
            eslint-plugin-react@~7.37.5
            eslint-plugin-react-hooks@~6.0.0-rc.1
            globals@~16.3.0
            typescript-eslint@~8.38.0
